version: 1

trail:
  attestations:
    - name: pull-request
      type: pull_request

  artifacts:
    - name: web
      attestations:
        - name: provenance-facts
          type: custom:provenance-facts
        - name: provenance-decision
          type: decision

        - name: sbom-facts
          type: custom:sbom-facts
        - name: sbom-decision
          type: decision

        - name: snyk-container-scan
          type: decision
