#!/bin/sh

install_url=http://blog.cyber-dojo.org/2016/03/running-your-own-cyber-dojo-server.html
my_dir="$( cd "$( dirname "${0}" )" && pwd )"
cyber_dojo_sh=cyber-dojo.sh

exit_if_docker_not_installed() {
  hash docker 2> /dev/null
  if [ $? != 0 ]; then
    echo
    echo 'docker is not installed'
    echo "See step 1 of ${install_url}"
    exit 1
  fi
}

exit_if_docker_machine_not_installed() {
  hash docker-machine 2> /dev/null
  if [ $? != 0 ]; then
    echo 'docker-machine is not installed'
    echo "See step 1 of ${install_url}"
    exit 1
  fi
}

exit_if_docker_compose_not_installed() {
  hash docker-compose 2> /dev/null
  if [ $? != 0 ]; then
    echo
    echo 'docker-compose is not installed'
    echo "See step 1 of ${install_url}"
    exit 1
  fi
}

cyber_dojo_update() {
  # cyber-dojo web server image is docker version sensitive.
  # See app/docker/web/Dockerfile ~ line 49
  #    docker --version  -->  Docker version 1.11.2, build 5604cbe
  #    awk '{print $3}'  -->  1.11.2,           (third field)
  #    sed '$s/.$//'     -->  1.11.2            (lose last comma)
  local docker_version=$(docker --version | awk '{print $3}' | sed '$s/.$//')
  local cyber_dojo_home=/usr/src/cyber-dojo
  local cyber_dojo_hub=cyberdojo
  local cyber_dojo_web_server=${cyber_dojo_hub}/web:${docker_version}
  local docker_compose_file=docker-compose.yml

  echo "GOT HERE"
  # update server images
  docker pull ${cyber_dojo_hub}/nginx:latest
  docker pull ${cyber_dojo_web_server}

  # extract cyber-dojo.sh from web image
  local cid=$(docker create ${cyber_dojo_web_server})
  docker cp ${cid}:${cyber_dojo_home}/app/docker/${cyber_dojo_sh} ${my_dir}/${cyber_dojo_sh}
  docker rm -v ${cid} > /dev/null

  # extract docker-compose.yml file from web image
  local cid=$(docker create ${cyber_dojo_web_server})
  docker cp ${cid}:${cyber_dojo_home}/app/docker/${docker_compose_file} ${my_dir}/${docker_compose_file}
  docker rm -v ${cid} > /dev/null
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

exit_if_docker_not_installed
exit_if_docker_machine_not_installed
exit_if_docker_compose_not_installed

if [ "$*" = "update" ]; then
  cyber_dojo_update
fi

export CYBER_DOJO_SCRIPT_WRAPPER=inprogress
${my_dir}/${cyber_dojo_sh} $@


