#!/bin/sh

my_dir="$( cd "$( dirname "${0}" )" && pwd )"

# cyber-dojo web server image is docker version sensitive.
# See docker/web/Dockerfile ~ line 49
#    docker --version  -->  Docker version 1.11.2, build 5604cbe
#    awk '{print $3}'  -->  1.11.2,           (third field)
#    sed '$s/.$//'     -->  1.11.2            (lose last comma)
docker_version=$(docker --version | awk '{print $3}' | sed '$s/.$//')

cyber_dojo_hub=cyberdojo
cyber_dojo_web_server=${cyber_dojo_hub}/web:${docker_version}

cyber_dojo_sh=cyber-dojo.sh
docker_compose_yml=docker-compose.yml

# - - - - - - - - - - - - - - - - - - - - - - -

exit_if_not_installed() {
  hash ${1} 2> /dev/null
  if [ $? != 0 ]; then
    echo
    echo "${1} is not installed"
    echo 'See step 1 of https://github.com/cyber-dojo/web/blob/master/README.md'
    exit 1
  fi
}

# - - - - - - - - - - - - - - - - - - - - - - -

get_file_from_web_image() {
  echo "Extracting ${1} from ${cyber_dojo_web_server}"
  local cid=$(docker create ${cyber_dojo_web_server})
  docker cp ${cid}:/usr/src/cyber-dojo/cli/${1} ${my_dir}/${1}
  docker rm -v ${cid} > /dev/null
}

# - - - - - - - - - - - - - - - - - - - - - - -

exit_if_not_installed 'docker'
exit_if_not_installed 'docker-machine'
exit_if_not_installed 'docker-compose'

if [ ! -f ${my_dir}/${cyber_dojo_sh} ]; then
  get_file_from_web_image ${cyber_dojo_sh}
fi

if [ ! -f ${my_dir}/${docker_compose_yml} ]; then
  get_file_from_web_image ${docker_compose_yml}
fi

if [ "$*" = "update" ]; then
  # update server images
  docker pull ${cyber_dojo_hub}/nginx:latest
  docker pull ${cyber_dojo_web_server}
  # extract new files
  get_file_from_web_image ${cyber_dojo_sh}
  get_file_from_web_image ${docker_compose_yml}
fi

export CYBER_DOJO_SCRIPT_WRAPPER=inprogress
${my_dir}/${cyber_dojo_sh} $@


