name: Base Image Update

on:
  repository_dispatch:
    types: [base-image-update]


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      base_image:  ${{ steps.vars.outputs.base_image }}
      kosli_trail: ${{ steps.vars.outputs.kosli_trail }}
    steps:
      - name: Outputs
        id: vars
        run: | 
          NAME="${{ github.event.client_payload.name }}"
          TAG="${{ github.event.client_payload.tag }}"
          DIGEST="${{ github.event.client_payload.digest }}"
          echo "base_image=${NAME}:${TAG}@sha256:${DIGEST}" >> ${GITHUB_OUTPUT}
          echo "kosli_trail=base-image-update-${TAG}"       >> ${GITHUB_OUTPUT}
      

  trigger:
    needs: [setup]
    uses: ./.github/workflows/main.yml
    with:
      BASE_IMAGE:  ${{ needs.setup.outputs.base_image }}
      KOSLI_TRAIL: ${{ needs.setup.outputs.kosli_trail }}
    secrets:
      DOCKER_USER:     ${{ secrets.DOCKER_USER }}
      DOCKER_PASS:     ${{ secrets.DOCKER_PASS }}
      SNYK_TOKEN:      ${{ secrets.SNYK_TOKEN }}
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}

